import '../globals.css'
import Header from '@/components/header'
import { pano } from '@/components/fonts'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${pano.variable} font-sans`}>
			<body className="bg-hlinoteka-dark text-hlinoteka-light px-4 sm:px-8 mx-auto">
				<Header />
				<div className="mt-20 overflow-hidden">
					{children}
				</div>
			</body>
		</html>
	)
}
